apiVersion: v1
kind: Blueprint
metadata:
  name: builtin-components
  label:
    en_US: Builtin Components
    zh_Hans: 内置组件
spec:
  components:
    ComponentTemplate:
      fromFiles:
        - pkg/platform/adapter.yaml
        - pkg/provider/modelmgr/requester.yaml
    MessagePlatformAdapter:
      fromDirs:
        - path: pkg/platform/sources/
    LLMAPIRequester:
      fromDirs:
        - path: pkg/provider/modelmgr/requesters/
    Plugin:
      fromDirs:
        - path: plugins/
          maxDepth: 2
