apiVersion: v1
kind: LLMAPIRequester
metadata:
  name: anthropic-messages
  label:
    en_US: Anthropic
    zh_Hans: Anthropic
  icon: anthropic.svg
spec:
  config:
    - name: base_url
      label:
        en_US: Base URL
        zh_Hans: 基础 URL
      type: string
      required: true
      default: "https://api.anthropic.com/v1"
    - name: timeout
      label:
        en_US: Timeout
        zh_Hans: 超时时间
      type: integer
      required: true
      default: 120
execution:
  python:
    path: ./anthropicmsgs.py
    attr: AnthropicMessages
